name: Deploy to Prod Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: Deploy code in Production site
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > ~/.ssh/id_rsa
        echo "---before---"
        ssh-keyscan -t rsa ${{ secrets.SSH_HOST_PROD }} > ~/.ssh/known_hosts
        echo "---after---"
        cat ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
    - name: Connect and Pull
      run: ssh ${{ secrets.SSH_USER_PROD }}@${{ secrets.SSH_HOST_PROD }} "cd ${{ secrets.WORK_DIR_PROD }} && git checkout . && git checkout ${{ secrets.BRANCH_PROD }} && git pull && exit" 